# Generated by Django 4.1 on 2023-02-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_team_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.CharField(max_length=200),
        ),
    ]
