# Generated by Django 4.1 on 2023-02-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0003_alter_team_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='mascot',
        ),
    ]
